---
- name: Deploy Docker Compose Application
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure working directory exists
      file:
        path: /home/ubuntu/docker-app
        state: directory

    - name: Copy Docker Compose file
      copy:
        src: docker/docker-compose.yml  
        dest: /home/ubuntu/docker-app/docker-compose.yml

    - name: Copy Flask app files
      copy:
        src: docker/web/ 
        dest: /home/ubuntu/docker-app/web/

    - name: Deploy application using Docker Compose
      command: docker-compose -f /home/ubuntu/docker-app/docker-compose.yml up -d
