name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_AUTH_LOCATION: ${{ secrets.AZURE_CREDENTIALS }}    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker Image
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login erezcontainerregistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker build -t erezcontainerregistry.azurecr.io/webapp:latest -f docker/Dockerfile .          
          docker push erezcontainerregistry.azurecr.io/webapp:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Install kubelogin
        run: |
          curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.25/kubelogin-linux-amd64.zip
          unzip kubelogin-linux-amd64.zip
          sudo mv bin/linux_amd64/kubelogin /usr/local/bin/

      - name: Configure Azure CLI to use service principal
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Get AKS credentials and Deploy to AKS
        run: |
          az aks get-credentials --resource-group Erez1-Candidate --name aks-cluster
          kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml
