name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Build Docker Image
        run: |
          docker build -t youracr.azurecr.io/webapp:latest .
          echo ${{ secrets.ACR_PASSWORD }} | docker login youracr.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push youracr.azurecr.io/webapp:latest
