name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker Image
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login erezcontainerregistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker build -t erezcontainerregistry.azurecr.io/webapp:latest -f docker/Dockerfile .          
          docker push erezcontainerregistry.azurecr.io/webapp:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Install kubelogin
        run: |
          curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.25/kubelogin-linux-amd64.zip
          unzip kubelogin-linux-amd64.zip
          sudo mv kubelogin /usr/local/bin/
                    
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group Erez1-Candidate --name aks-cluster

      - name: Deploy to AKS
        run: kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml