name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker Image
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login erezcontainerregistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker build -t erezcontainerregistry.azurecr.io/webapp:latest .          
          docker push erezcontainerregistry.azurecr.io/webapp:latest
